### ISSUE TITLE
Missing sensors?

### ISSUE THREAD

**Issue by gdotp01** [megakid/ha_octopus_intelligent#21]
Hi.
This is probably a dumb question but I’ve spent some time trying to work it out. I’ve deleted the integration and reinstalled it.
The documentation says there are dispatch slots that I presume are populated when the charge schedule is 
set up. However I can’t see any of these, the sensors are missing. My list is as per the attached screenshot 
![IMG_0798](https://github.com/megakid/ha_octopus_intelligent/assets/50060482/2f70aaed-e943-4439-9574-8d2d558f5a92)

**Comment by gdotp01** [comment]
Logger: homeassistant.components.binary_sensor Source: custom_components/octopus_intelligent/binary_sensor.py:100 Integration: Binary sensor ([documentation](https://www.home-assistant.io/integrations/binary_sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+binary_sensor%22)) First occurred: 7:51:41 PM (1 occurrences) Last logged: 7:51:41 PM
Error while setting up octopus_intelligent platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 320, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/octopus_intelligent/binary_sensor.py", line 19, in async_setup_entry
    OctopusIntelligentSlot(
  File "/config/custom_components/octopus_intelligent/binary_sensor.py", line 59, in __init__
    self._timer = async_track_utc_time_change(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1628, in async_track_utc_time_change
    f"time change listener {hour}:{minute}:{second} {action}",
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1026, in __repr__
    return f"<entity {self.entity_id}={self._stringify_state(self.available)}>"
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 596, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 211, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/octopus_intelligent/binary_sensor.py", line 100, in is_on
    return self._is_on
           ^^^^^^^^^^^
AttributeError: 'OctopusIntelligentSlot' object has no attribute '_is_on'

**Comment by gdotp01** [comment]
I downloaded earlier today. Tonight  there seemed to be a version number update so i decide to give that a go and the sensors have returned.

**Comment by dtpazz** [comment]
Version hasn't changed since June. These threads are for issues not general support.

**Comment by gdotp01** [comment]
I reported an issue. Provided some log information and then last night whist investigating what the problem was downloaded a newer version. After that I closed the issue.
