### ISSUE TITLE
Integration Failing Setup

### ISSUE THREAD

**Issue by NickSutton** [megakid/ha_octopus_intelligent#23]
Attempting to register the integration, wizard just reloads with blank API and ID fields when submitted, the following is in the log:

````
Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/octopus_intelligent/config_flow.py", line 61, in async_step_user
    await self.hass.async_add_executor_job(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 587, in async_add_executor_job
    task = self.loop.run_in_executor(None, target, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 818, in run_in_executor
    self._check_callback(func, 'run_in_executor')
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 773, in _check_callback
    raise TypeError(
TypeError: coroutines cannot be used with run_in_executor()
````

**Comment by stevebuk1** [comment]
Same problem for me.
